### PR TITLE
Scale factor hack

### PR DESCRIPTION
**Pull request by aappling-usgs**
I think this PR gets us final numbers that can be used to generate plots. I also rebuilt the old plots to confirm that this PR fixes https://github.com/USGS-R/protoloads/issues/68.

### CODE REVIEW

**Comment by aappling-usgs** [comment]
The rebuilt plots:

inputs:
fig_input_data

preds - loadest:
fig_preds_v_time_loadest

preds - wrtds:
fig_preds_v_time_wrtds

errors v lead time
 - wrtds:
fig_error_v_leadtime

**Comment by jzwart** [comment]
looks good but there are conflicts with indicator files and builds. I think because I built these and pushed in last PR. Yours are more recent builds though

**Comment by aappling-usgs** [comment]
I think I have the merge conflicts straightened out now. remake says everything is up to date for me (except 3_forecast.yml, which is intentional for now as noted in https://github.com/USGS-R/protoloads/issues/70)

**Comment by aappling-usgs** [comment]
PS - @jzwart I like your color scheme. Not gonna worry about carrying it over to the older plots quite yet, but I'm on board and we can work on unifying the plot styles toward that scheme later :+1:

**Comment by jzwart** [comment]
sounds good! we should also think about colors used for flow vs. model range vs. lead time

**Pull request merged**
