### PR TITLE
Rerun models

### PR DESCRIPTION
**Pull request by aappling-usgs**
Models are done!

I'm rebuilding the figures now but think I'd better put those in a separate PR...preds_v_time seems to have acquired mismatched magnitudes for the NWIS vs NWM/loadmodel values, which will need some investigation. Preview of the other two looks good, though, I think:

fig_error_v_leadtime

fig_input_data

### CODE REVIEW

**Comment by aappling-usgs** [comment]
Only...are those magnitudes right? Here are our plots from 5/30 (error_v_leadtime) and 5/21 (input_data):

fig_error_v_leadtime
^ relative errors are approximately 100x higher in today's plots than they were in this one

fig_input_data 2
^ discharge and flux are both 100x higher in today's plots than they were in this one

**Comment by jzwart** [comment]
cool! is there a unit conversion issue?

**Comment by jzwart** [comment]
ah I see you made an issue for units :)

**Comment by aappling-usgs** [comment]
Yes, I think the units issue is now captured in #68.

**Comment by jzwart** [comment]
do you want to add a divide by 100 in `gather_forecasts` to this PR @aappling-usgs ?

**Comment by jread-usgs** [comment]
this is so cool!

**Comment by aappling-usgs** [comment]
@jzwart - lemme do that as a second PR so it's really clear how to adjust it later when i have time to rerun the models. i'm ready to merge this PR if you are.

**Comment by jzwart** [comment]
sounds good, will merge

**Pull request merged**
